### PR TITLE
branch commands fixes

### PR DESCRIPTION
**Pull request by GuillaumeBibaut**
- handle merge revisions argument separately, more simple regex
- added a SVN Merge reintegrate to the menu and commands
- fix the 'SVN > Branch', svn copy needs a commit message

I don't know if it is possible or not for you to reintegrate all these changes, but I found myself wondering why the merge command was not working for me so I have tried to fix it and enhance it by handling revisions arguments separately.
Also, I've occurred to need the 'svn --reintegrate' command, so I've used inheritance and created a new entry to the menu with a new command 'SVN Merge reintegrate', which is supposed to work nice when reintegrating a SVN branch to its origin (trunk or other origin branch name).
And there was a problem with the Branch command because even if most svn commands can be executed in non-interactive mode, the 'svn copy' command needs a commit message to create a branch.

If this is too much in one pull, I can also break this in many branch so that you can reintegrate these sequentially. I just though it would be better in one pull because the main impacted file is `branch_commands.py`.

### CODE REVIEW

**Comment by m-hall** [comment]
Everything looks good, the only thing I'd like to you change is the tests for the reintegrate command. It should be for native only instead of just enabled as the tortoise command for merge handles all different kinds of merging.

In the future I do prefer separating pull requests, however that's only so that if I have to send one thing back I can still pull the other changes in, so I won't reject it just for that. Also it helps to be able to see which changes in the files are for which request.

**Comment by GuillaumeBibaut** [comment]
I've added the run override to check for native and not to try to launch the TortoiseSVN merge command instead for the reintegrate. I'm mostly working on Mac OS, that's why I didn't see that. I've got a Windows PC at home, so I'll try to test this and try to implement the reintegrate for TortoiseSVN later.

**Comment by GuillaumeBibaut** [comment]
oups my bad, I didn't see I had merged a branch in my master yesterday.... I'm trying to fix this.

**Comment by m-hall** [comment]
You actually don't need to implement the merge-reintegrate for tortoise, as I said, the merge command for tortoise handles all kinds of merges. Just set the tests object in the constructor to "native" instead of "enabled"

**Comment by GuillaumeBibaut** [comment]
First, I have to apologize because I had merged some branch into my local master and forgot that point when I pushed my local master to GitHub this morning. I think I've fixed this problem with a rebase, but at first I thought I had crashed my git repo. Sorry about that.

About the merge reintegrate, what I understand here is that I don't need to make something like I did in the `native only SVN Merge reintegrate`, and instead I just have to set the 'native' property in the tests object to True, and delete the 'enabled' one ? (I think I need to understand better the patterns used here).

**Comment by m-hall** [comment]
Yes, the goal is to make the merge-reintegrate command invisible when merge is using tortoise, because tortoise only needs 1 command for merging.

This will work similar to the Log and Log N commands, where if Log is using tortoise, then the Log N command is not visible. You will likely need to add the is_visible method in the same way Log N has it so that merge-reintegrate will check if "merge" does not prefer tortoise.

**Comment by m-hall** [comment]
In reality I should probably actually just add the prefer check to the tests property anyway so that it's not necessary to add special is_visible functions for so many commands.

On second thought, I think I'll merge your changes now and then do that.

**Comment by GuillaumeBibaut** [comment]
I think I understand what you mean :)
Thanks for the merge :+1:

**Comment by m-hall** [comment]
So just a little FYI: I realized that Merge Reintegrate does not allow picking revisions, so I've removed them from the reintegrate command.
I've also moved the command to the sub-menu where switch and branch exist to avoid clutter. Mostly because reintegrate is a much less commonly used command.

**Pull request merged**
